package co.wishroll.views.reusables;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageButton;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import co.wishroll.R;

import static android.view.View.GONE;

public class TextBodyActivity extends AppCompatActivity {
    private static final String TAG = "TextBodyActivity";
    ImageButton backButton;
    TextView mainTitle, privacyPolicyBody;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_textbody);
        //for viewing privacy policy and frequently asked questions
        boolean isFAQ = getIntent().getBooleanExtra("isFAQ", true);
        mainTitle = findViewById(R.id.textBodyMainTitle);
        backButton = findViewById(R.id.backButtonTextBody);
        privacyPolicyBody = findViewById(R.id.privacyPolicyMainText);
        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onBackPressed();
            }
        });

        String lol = "Effective date: 02/05/2020\n" +
                "1. Introduction\n" +
                "\n" +
                "Welcome to WishRoll Inc.\n" +
                "\n" +
                "WishRoll Inc. (“us”, “we”, or “our”) operates WishRoll mobile application (hereinafter referred\n" +
                "to as “Service”).\n" +
                "\n" +
                "Our Privacy Policy governs your visit to WishRoll mobile application, and explains how we\n" +
                "collect, safeguard and disclose information that results from your use of our Service.\n" +
                "We use your data to provide and improve Service. By using Service, you agree to the\n" +
                "collection and use of information in accordance with this policy. Unless otherwise defined in\n" +
                "this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our\n" +
                "Terms and Conditions.\n" +
                "\n" +
                "Our Terms and Conditions (“Terms”) govern all use of our Service and together with the\n" +
                "Privacy Policy constitutes your agreement with us (“agreement”).\n" +
                "\n" +
                "\n" +
                "2. Definitions\n" +
                "SERVICE means the WishRoll mobile application operated by WishRoll Inc.\n" +
                "PERSONAL DATA means data about a living individual who can be identified from those\n" +
                "data (or from those and other information either in our possession or likely to come into our\n" +
                "possession).\n" +
                "USAGE DATA is data collected automatically either generated by the use of Service or from\n" +
                "Service infrastructure itself (for example, the duration of a page visit).\n" +
                "COOKIES are small files stored on your device (computer or mobile device).\n" +
                "DATA CONTROLLER means a natural or legal person who (either alone or jointly or in\n" +
                "common with other persons) determines the purposes for which and the manner in which\n" +
                "any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we\n" +
                "are a Data Controller of your data.\n" +
                "DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who\n" +
                "processes the data on behalf of the Data Controller. We may use the services of various\n" +
                "Service Providers in order to process your data more effectively.\n" +
                "DATA SUBJECT is any living individual who is the subject of Personal Data.\n" +
                "THE USER is the individual using our Service. The User corresponds to the Data Subject,\n" +
                "who is the subject of Personal Data.\n" +
                "\n" +
                "3. Information Collection and Use\n" +
                "\n" +
                "2\n" +
                "We collect several different types of information for various purposes to provide and improve\n" +
                "our Service to you.\n" +
                "\n" +
                "\n" +
                "4. Types of Data Collected\n" +
                "Personal Data\n" +
                "While using our Service, we may ask you to provide us with certain personally identifiable\n" +
                "information that can be used to contact or identify you (“Personal Data”). Personally\n" +
                "identifiable information may include, but is not limited to:\n" +
                "(a) Email address\n" +
                "(b) Cookies and Usage Data\n" +
                "We may use your Personal Data to contact you with newsletters, marketing or promotional\n" +
                "materials and other information that may be of interest to you. You may opt out of receiving\n" +
                "any, or all, of these communications from us by following the unsubscribe link or by emailing\n" +
                "at support@wishroll.co.\n" +
                "\n" +
                "Usage Data\n" +
                "We may also collect information that your browser sends whenever you visit our Service or\n" +
                "when you access Service by or through a mobile device (“Usage Data”).\n" +
                "This Usage Data may include information such as your computer&#39;s Internet Protocol address\n" +
                "(e.g. IP address), browser type, browser version, the pages of our Service that you visit, the\n" +
                "time and date of your visit, the time spent on those pages, unique device identifiers and\n" +
                "other diagnostic data.\n" +
                "When you access Service with a mobile device, this Usage Data may include information\n" +
                "such as the type of mobile device you use, your mobile device unique ID, the IP address of\n" +
                "your mobile device, your mobile operating system, the type of mobile Internet browser you\n" +
                "use, unique device identifiers and other diagnostic data.\n" +
                "\n" +
                "Tracking Cookies Data\n" +
                "We use cookies and similar tracking technologies to track the activity on our Service and we\n" +
                "hold certain information.\n" +
                "Cookies are files with a small amount of data which may include an anonymous unique\n" +
                "identifier. Cookies are sent to your browser from a website and stored on your device. Other\n" +
                "tracking technologies are also used such as beacons, tags and scripts to collect and track\n" +
                "information and to improve and analyze our Service.\n" +
                "You can instruct your browser to refuse all cookies or to indicate when a cookie is being\n" +
                "sent. However, if you do not accept cookies, you may not be able to use some portions of\n" +
                "our Service.\n" +
                "\n" +
                "Examples of Cookies we use:\n" +
                "(a) Session Cookies: We use Session Cookies to operate our Service.\n" +
                "\n" +
                "3\n" +
                "(b) Preference Cookies: We use Preference Cookies to remember your preferences and\n" +
                "various settings.\n" +
                "(c) Security Cookies: We use Security Cookies for security purposes.\n" +
                "(d) Advertising Cookies: Advertising Cookies are used to serve you with advertisements\n" +
                "that may be relevant to you and your interests.\n" +
                "\n" +
                "\n" +
                "5. Use of Data\n" +
                "WishRoll Inc. uses the collected data for various purposes:\n" +
                "(a) to provide and maintain our Service;\n" +
                "(b) to notify you about changes to our Service;\n" +
                "(c) to allow you to participate in interactive features of our Service when you choose to do\n" +
                "so;\n" +
                "(d) to provide customer support;\n" +
                "(e) to gather analysis or valuable information so that we can improve our Service;\n" +
                "(f) to monitor the usage of our Service;\n" +
                "(g) to detect, prevent and address technical issues;\n" +
                "(h) to fulfill any other purpose for which you provide it;\n" +
                "(i) to carry out our obligations and enforce our rights arising from any contracts entered into\n" +
                "between you and us, including for billing and collection;\n" +
                "(j) to provide you with notices about your account and/or subscription, including expiration\n" +
                "and renewal notices, email-instructions, etc.;\n" +
                "(k) to provide you with news, special offers and general information about other goods,\n" +
                "services and events which we offer that are similar to those that you have already\n" +
                "purchased or enquired about unless you have opted not to receive such information;\n" +
                "(l) in any other way we may describe when you provide the information;\n" +
                "(m) for any other purpose with your consent.\n" +
                "\n" +
                "\n" +
                "4\n" +
                "\n" +
                "6. Retention of Data\n" +
                "We will retain your Personal Data only for as long as is necessary for the purposes set out in\n" +
                "this Privacy Policy. We will retain and use your Personal Data to the extent necessary to\n" +
                "comply with our legal obligations (for example, if we are required to retain your data to\n" +
                "comply with applicable laws), resolve disputes, and enforce our legal agreements and\n" +
                "policies.\n" +
                "We will also retain Usage Data for internal analysis purposes. Usage Data is generally\n" +
                "retained for a shorter period, except when this data is used to strengthen the security or to\n" +
                "improve the functionality of our Service, or we are legally obligated to retain this data for\n" +
                "longer time periods.\n" +
                "\n" +
                "7. Transfer of Data\n" +
                "Your information, including Personal Data, may be transferred to – and maintained on –\n" +
                "computers located outside of your state, province, country or other governmental jurisdiction\n" +
                "where the data protection laws may differ from those of your jurisdiction.\n" +
                "If you are located outside United States and choose to provide information to us, please\n" +
                "note that we transfer the data, including Personal Data, to United States and process it\n" +
                "there.\n" +
                "\n" +
                "Your consent to this Privacy Policy followed by your submission of such information\n" +
                "represents your agreement to that transfer.\n" +
                "WishRoll Inc. will take all the steps reasonably necessary to ensure that your data is treated\n" +
                "securely and in accordance with this Privacy Policy and no transfer of your Personal Data\n" +
                "will take place to an organisation or a country unless there are adequate controls in place\n" +
                "including the security of your data and other personal information.\n" +
                "\n" +
                "8. Disclosure of Data\n" +
                "We may disclose personal information that we collect, or you provide:\n" +
                "(a) Business Transaction.\n" +
                "If we or our subsidiaries are involved in a merger, acquisition or asset sale, your\n" +
                "Personal Data may be transferred.\n" +
                "(b) Other cases. We may disclose your information also:\n" +
                "(i) to our subsidiaries and affiliates;\n" +
                "(ii) to contractors, service providers, and other third parties we use to support our\n" +
                "business;\n" +
                "(iii) to fulfill the purpose for which you provide it;\n" +
                "(iv) with your consent in any other cases;\n" +
                "\n" +
                "\n" +
                "5\n" +
                "(v) if we believe disclosure is necessary or appropriate to protect the rights, property, or\n" +
                "safety of the Company, our customers, or others.\n" +
                "\n" +
                "\n" +
                "9. Security of Data\n" +
                "The security of your data is important to us but remember that no method of transmission\n" +
                "over the Internet or method of electronic storage is 100% secure. While we strive to use\n" +
                "commercially acceptable means to protect your Personal Data, we cannot guarantee its\n" +
                "absolute security.\n" +
                "\n" +
                "10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)\n" +
                "If you are a resident of the European Union (EU) and European Economic Area (EEA), you\n" +
                "have certain data protection rights, covered by GDPR. – See more at https://eur-\n" +
                "lex.europa.eu/eli/reg/2016/679/oj\n" +
                "We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of\n" +
                "your Personal Data.\n" +
                "\n" +
                "If you wish to be informed what Personal Data we hold about you and if you want it to be\n" +
                "removed from our systems, please delete your account\n" +
                "In certain circumstances, you have the following data protection rights:\n" +
                "(a) the right to access, update or to delete the information we have on you;\n" +
                "(b) the right of rectification. You have the right to have your information rectified if that\n" +
                "information is inaccurate or incomplete;\n" +
                "(c) the right to object. You have the right to object to our processing of your Personal Data;\n" +
                "(d) the right of restriction. You have the right to request that we restrict the processing of\n" +
                "your personal information;\n" +
                "(e) the right to data portability. You have the right to be provided with a copy of your\n" +
                "Personal Data in a structured, machine-readable and commonly used format;\n" +
                "(f) the right to withdraw consent. You also have the right to withdraw your consent at any\n" +
                "time where we rely on your consent to process your personal information;\n" +
                "Please note that we may ask you to verify your identity before responding to such requests.\n" +
                "Please note, we may not able to provide Service without some necessary data.\n" +
                "You have the right to complain to a Data Protection Authority about our collection and use of\n" +
                "your Personal Data. For more information, please contact your local data protection\n" +
                "authority in the European Economic Area (EEA).\n" +
                "11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)\n" +
                "CalOPPA is the first state law in the nation to require commercial websites and online\n" +
                "services to post a privacy policy. The law’s reach stretches well beyond California to require\n" +
                "\n" +
                "\n" +
                "6\n" +
                "a person or company in the United States (and conceivable the world) that operates\n" +
                "websites collecting personally identifiable information from California consumers to post a\n" +
                "conspicuous privacy policy on its website stating exactly the information being collected and\n" +
                "those individuals with whom it is being shared, and to comply with this policy. – See more at:\n" +
                "https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-\n" +
                "protection-act-caloppa-3/\n" +
                "\n" +
                "According to CalOPPA we agree to the following:\n" +
                "(a) users can visit our site anonymously;\n" +
                "(b) our Privacy Policy link includes the word “Privacy”, and can easily be found on the page\n" +
                "specified above on the home page of our website;\n" +
                "(c) users will be notified of any privacy policy changes on our Privacy Policy Page;\n" +
                "Our Policy on “Do Not Track” Signals:\n" +
                "We honor Do Not Track signals and do not track, plant cookies, or use advertising when a\n" +
                "Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in\n" +
                "your web browser to inform websites that you do not want to be tracked.\n" +
                "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your\n" +
                "web browser.\n" +
                "\n" +
                "12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)\n" +
                "If you are a California resident, you are entitled to learn what data we collect about you, ask\n" +
                "to delete your data and not to sell (share) it. To exercise your data protection rights, you can\n" +
                "make certain requests and ask us:\n" +
                "(a) What personal information we have about you. If you make this request, we will\n" +
                "return to you:\n" +
                "(i) The categories of personal information we have collected about you.\n" +
                "(ii) The categories of sources from which we collect your personal information.\n" +
                "(iii) The business or commercial purpose for collecting or selling your personal\n" +
                "information.\n" +
                "(iv) The categories of third parties with whom we share personal information.\n" +
                "(v) The specific pieces of personal information we have collected about you.\n" +
                "(vi) A list of categories of personal information that we have sold, along with the category\n" +
                "of any other company we sold it to. If we have not sold your personal information, we\n" +
                "will inform you of that fact.\n" +
                "\n" +
                "\n" +
                "7\n" +
                "(vii) A list of categories of personal information that we have disclosed for a business\n" +
                "purpose, along with the category of any other company we shared it with.\n" +
                "Please note, you are entitled to ask us to provide you with this information up to two\n" +
                "times in a rolling twelve-month period. When you make this request, the information\n" +
                "provided may be limited to the personal information we collected about you in the\n" +
                "previous 12 months.\n" +
                "\n" +
                "(b) To delete your personal information. If you make this request, we will delete the\n" +
                "personal information we hold about you as of the date of your request from our records\n" +
                "and direct any service providers to do the same. In some cases, deletion may be\n" +
                "accomplished through de-identification of the information. If you choose to delete your\n" +
                "personal information, you may not be able to use certain functions that require your\n" +
                "personal information to operate.\n" +
                "\n" +
                "(c) To stop selling your personal information. We do not sell your personal information\n" +
                "for monetary consideration. However, under some circumstances, a transfer of personal\n" +
                "information to a third party, or within our family of companies, without monetary\n" +
                "consideration may be considered a “sale” under California law.\n" +
                "If you submit a request to stop selling your personal information, we will stop making\n" +
                "such transfers. If you are a California resident, to opt-out of the sale of your personal\n" +
                "information, click “Do Not Sell My Personal Information” at the bottom of our home page\n" +
                "to submit your request.\n" +
                "\n" +
                "To exercise your California data protection rights described above, please send your\n" +
                "request(s) by one of the following means:\n" +
                "By email: support@wishroll.co\n" +
                "By visiting this page on our website: https://wishroll.co/contact\n" +
                "Your data protection rights, described above, are covered by the CCPA, short for the\n" +
                "California Consumer Privacy Act. To find out more, visit the official California Legislative\n" +
                "Information website. The CCPA took effect on 01/01/2020.\n" +
                "13. Service Providers\n" +
                "\n" +
                "We may employ third party companies and individuals to facilitate our Service (“Service\n" +
                "Providers”), provide Service on our behalf, perform Service-related services or assist us in\n" +
                "analysing how our Service is used.\n" +
                "These third parties have access to your Personal Data only to perform these tasks on our\n" +
                "behalf and are obligated not to disclose or use it for any other purpose.\n" +
                "\n" +
                "\n" +
                "8\n" +
                "\n" +
                "14. Analytics\n" +
                "We may use third-party Service Providers to monitor and analyze the use of our Service.\n" +
                "\n" +
                "Firebase\n" +
                "Firebase is analytics service provided by Google Inc.\n" +
                "You may opt-out of certain Firebase features through your mobile device settings, such as\n" +
                "your device advertising settings or by following the instructions provided by Google in their\n" +
                "Privacy Policy: https://policies.google.com/privacy?hl=en\n" +
                "For more information on what type of information Firebase collects, please visit the Google\n" +
                "Privacy Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "Mixpanel\n" +
                "Mixpanel is provided by Mixpanel Inc.\n" +
                "You can prevent Mixpanel from using your information for analytics purposes by opting-out.\n" +
                "To opt-out of Mixpanel service, please visit this page: https://mixpanel.com/optout/\n" +
                "For more information on what type of information Mixpanel collects, please visit the Terms of\n" +
                "Use page of Mixpanel: https://mixpanel.com/terms/\n" +
                "15. CI/CD tools\n" +
                "We may use third-party Service Providers to automate the development process of our\n" +
                "Service.\n" +
                "\n" +
                "GitHub\n" +
                "GitHub is provided by GitHub, Inc.\n" +
                "GitHub is a development platform to host and review code, manage projects, and build\n" +
                "software.\n" +
                "\n" +
                "For more information on what data GitHub collects for what purpose and how the protection\n" +
                "of the data is ensured, please visit GitHub Privacy Policy page:\n" +
                "https://help.github.com/en/articles/github-privacy-statement.\n" +
                "GitLab CI/CD\n" +
                "GitLab CI/CD is provided by GitLab, Inc.\n" +
                "GitLab CI (Continuous Integration) service is a part of GitLab that build and test the software\n" +
                "whenever developer pushes code to application.\n" +
                "GitLab CD (Continuous Deployment) is a software service that places the changes of every\n" +
                "code in the production which results in every day deployment of production.\n" +
                "\n" +
                "9\n" +
                "For more information on what data GitLab CI/CD collects for what purpose and how the\n" +
                "protection of the data is ensured, please visit GitLab CI/CD Privacy Policy page:\n" +
                "https://about.gitlab.com/privacy/.\n" +
                "\n" +
                "16. Advertising\n" +
                "We may use third-party Service Providers to show advertisements to you to help support\n" +
                "and maintain our Service.\n" +
                "\n" +
                "Google AdSense DoubleClick Cookie\n" +
                "Google, as a third party vendor, uses cookies to serve ads on our Service. Google&#39;s use of\n" +
                "the DoubleClick cookie enables it and its partners to serve ads to our users based on their\n" +
                "visit to our Service or other websites on the Internet.\n" +
                "You may opt out of the use of the DoubleClick Cookie for interest-based advertising by\n" +
                "visiting the Google Ads Settings web page: http://www.google.com/ads/preferences/\n" +
                "\n" +
                "AdMob by Google\n" +
                "AdMob by Google is provided by Google Inc.\n" +
                "You can opt-out from the AdMob by Google service by following the instructions described\n" +
                "by Google: https://support.google.com/ads/answer/2662922?hl=en\n" +
                "For more information on how Google uses the collected information, please visit the “How\n" +
                "Google uses data when you use our partners&#39; sites or app” page:\n" +
                "http://www.google.com/policies/privacy/partners/ or visit the Privacy Policy of Google:\n" +
                "http://www.google.com/policies/privacy/\n" +
                "\n" +
                "17. Behavioral Remarketing\n" +
                "WishRoll Inc. uses remarketing services to advertise on third party websites to you after you\n" +
                "visited our Service. We and our third-party vendors use cookies to inform, optimise and\n" +
                "serve ads based on your past visits to our Service.\n" +
                "\n" +
                "Google Ads (AdWords)\n" +
                "Google Ads (AdWords) remarketing service is provided by Google Inc.\n" +
                "You can opt-out of Google Analytics for Display Advertising and customize the Google\n" +
                "Display Network ads by visiting the Google Ads Settings page:\n" +
                "http://www.google.com/settings/ads\n" +
                "Google also recommends installing the Google Analytics Opt-out Browser Add-on –\n" +
                "https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out\n" +
                "Browser Add-on provides visitors with the ability to prevent their data from being collected\n" +
                "and used by Google Analytics.\n" +
                "For more information on the privacy practices of Google, please visit the Google Privacy\n" +
                "\n" +
                "Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "\n" +
                "Facebook\n" +
                "\n" +
                "Facebook remarketing service is provided by Facebook Inc.\n" +
                "\n" +
                "10\n" +
                "You can learn more about interest-based advertising from Facebook by visiting this page:\n" +
                "https://www.facebook.com/help/164968693837950\n" +
                "To opt-out from Facebook&#39;s interest-based ads, follow these instructions from Facebook:\n" +
                "https://www.facebook.com/help/568137493302217\n" +
                "Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising\n" +
                "established by the Digital Advertising Alliance. You can also opt-out from Facebook and\n" +
                "other participating companies through the Digital Advertising Alliance in the USA\n" +
                "http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada\n" +
                "http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe\n" +
                "http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.\n" +
                "For more information on the privacy practices of Facebook, please visit Facebook&#39;s Data\n" +
                "Policy: https://www.facebook.com/privacy/explanation\n" +
                "\n" +
                "18. Payments\n" +
                "We may provide paid products and/or services within Service. In that case, we use third-\n" +
                "party services for payment processing (e.g. payment processors).\n" +
                "We will not store or collect your payment card details. That information is provided directly to\n" +
                "our third-party payment processors whose use of your personal information is governed by\n" +
                "their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as\n" +
                "managed by the PCI Security Standards Council, which is a joint effort of brands like Visa,\n" +
                "Mastercard, American Express and Discover. PCI-DSS requirements help ensure the\n" +
                "secure handling of payment information.\n" +
                "The payment processors we work with are:\n" +
                "\n" +
                "PayPal or Braintree:\n" +
                "Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full\n" +
                "\n" +
                "Stripe:\n" +
                "Their Privacy Policy can be viewed at: https://stripe.com/us/privacy\n" +
                "\n" +
                "19. Links to Other Sites\n" +
                "Our Service may contain links to other sites that are not operated by us. If you click a third\n" +
                "party link, you will be directed to that third party&#39;s site. We strongly advise you to review the\n" +
                "Privacy Policy of every site you visit.\n" +
                "\n" +
                "We have no control over and assume no responsibility for the content, privacy policies or\n" +
                "practices of any third party sites or services.\n" +
                "\n" +
                "20. Children&#39;s Privacy\n" +
                "Our Services are not intended for use by children under the age of 13 (“Children”).\n" +
                "\n" +
                "11\n" +
                "We do not knowingly collect personally identifiable information from Children under 13. If\n" +
                "you become aware that a Child has provided us with Personal Data, please contact us. If we\n" +
                "become aware that ce have collected Personal Data from Children without verification of\n" +
                "parental consent, we take steps to remove that information from our servers.\n" +
                "\n" +
                "21. Changes to This Privacy Policy\n" +
                "We may update our Privacy Policy from time to time. We will notify you of any changes by\n" +
                "posting the new Privacy Policy on this page.\n" +
                "We will let you know via email and/or a prominent notice on our Service, prior to the change\n" +
                "becoming effective and update “effective date” at the top of this Privacy Policy.\n" +
                "You are advised to review this Privacy Policy periodically for any changes. Changes to this\n" +
                "Privacy Policy are effective when they are posted on this page.\n" +
                "\n" +
                "22. Contact Us\n" +
                "If you have any questions about this Privacy Policy, please contact us:\n" +
                "By email: support@wishroll.co.\n" +
                "By visiting this page on our website: https://wishroll.co/contact.";

        if(isFAQ){
            //view faq text
            mainTitle.setText(getResources().getString(R.string.faqs));
            findViewById(R.id.faqTextBody).setVisibility(View.VISIBLE);
            findViewById(R.id.privacyPolicyText).setVisibility(GONE);
            privacyPolicyBody.setVisibility(View.GONE);

        }else{
            mainTitle.setText(getResources().getString(R.string.privacy_policy));
            findViewById(R.id.privacyPolicyText).setVisibility(View.VISIBLE);
            findViewById(R.id.faqTextBody).setVisibility(GONE);
            privacyPolicyBody.setVisibility(View.VISIBLE);
            privacyPolicyBody.setText(lol);
            Log.d(TAG, "onCreate: PRIVACY POLICY HOPEFULLY ITS ESCAPED ");
            //view privacy policy stuff
        }
    }
}