package co.wishroll.views.reusables;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageButton;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import co.wishroll.R;

import static android.view.View.GONE;

public class TextBodyActivity extends AppCompatActivity {
    private static final String TAG = "TextBodyActivity";
    ImageButton backButton;
    TextView mainTitle, privacyPolicyBody;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_textbody);
        //for viewing privacy policy and frequently asked questions
        int pageTitle = getIntent().getIntExtra("pageTitle", -1);

        mainTitle = findViewById(R.id.textBodyMainTitle);
        backButton = findViewById(R.id.backButtonTextBody);
        privacyPolicyBody = findViewById(R.id.privacyPolicyMainText);
        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onBackPressed();
            }
        });

        String lol = "Effective date: 02/05/2020\n" +
                "1. Introduction\n" +
                "\n" +
                "Welcome to WishRoll Inc.\n" +
                "\n" +
                "WishRoll Inc. (“us”, “we”, or “our”) operates WishRoll mobile application (hereinafter referred\n" +
                "to as “Service”).\n" +
                "\n" +
                "Our Privacy Policy governs your visit to WishRoll mobile application, and explains how we\n" +
                "collect, safeguard and disclose information that results from your use of our Service.\n" +
                "We use your data to provide and improve Service. By using Service, you agree to the\n" +
                "collection and use of information in accordance with this policy. Unless otherwise defined in\n" +
                "this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our\n" +
                "Terms and Conditions.\n" +
                "\n" +
                "Our Terms and Conditions (“Terms”) govern all use of our Service and together with the\n" +
                "Privacy Policy constitutes your agreement with us (“agreement”).\n" +
                "\n" +
                "\n" +
                "2. Definitions\n" +
                "SERVICE means the WishRoll mobile application operated by WishRoll Inc.\n" +
                "PERSONAL DATA means data about a living individual who can be identified from those\n" +
                "data (or from those and other information either in our possession or likely to come into our\n" +
                "possession).\n" +
                "USAGE DATA is data collected automatically either generated by the use of Service or from\n" +
                "Service infrastructure itself (for example, the duration of a page visit).\n" +
                "COOKIES are small files stored on your device (computer or mobile device).\n" +
                "DATA CONTROLLER means a natural or legal person who (either alone or jointly or in\n" +
                "common with other persons) determines the purposes for which and the manner in which\n" +
                "any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we\n" +
                "are a Data Controller of your data.\n" +
                "DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who\n" +
                "processes the data on behalf of the Data Controller. We may use the services of various\n" +
                "Service Providers in order to process your data more effectively.\n" +
                "DATA SUBJECT is any living individual who is the subject of Personal Data.\n" +
                "THE USER is the individual using our Service. The User corresponds to the Data Subject,\n" +
                "who is the subject of Personal Data.\n" +
                "\n" +
                "3. Information Collection and Use\n" +
                "\n" +
                "2\n" +
                "We collect several different types of information for various purposes to provide and improve\n" +
                "our Service to you.\n" +
                "\n" +
                "\n" +
                "4. Types of Data Collected\n" +
                "Personal Data\n" +
                "While using our Service, we may ask you to provide us with certain personally identifiable\n" +
                "information that can be used to contact or identify you (“Personal Data”). Personally\n" +
                "identifiable information may include, but is not limited to:\n" +
                "(a) Email address\n" +
                "(b) Cookies and Usage Data\n" +
                "We may use your Personal Data to contact you with newsletters, marketing or promotional\n" +
                "materials and other information that may be of interest to you. You may opt out of receiving\n" +
                "any, or all, of these communications from us by following the unsubscribe link or by emailing\n" +
                "at support@wishroll.co.\n" +
                "\n" +
                "Usage Data\n" +
                "We may also collect information that your browser sends whenever you visit our Service or\n" +
                "when you access Service by or through a mobile device (“Usage Data”).\n" +
                "This Usage Data may include information such as your computer&#39;s Internet Protocol address\n" +
                "(e.g. IP address), browser type, browser version, the pages of our Service that you visit, the\n" +
                "time and date of your visit, the time spent on those pages, unique device identifiers and\n" +
                "other diagnostic data.\n" +
                "When you access Service with a mobile device, this Usage Data may include information\n" +
                "such as the type of mobile device you use, your mobile device unique ID, the IP address of\n" +
                "your mobile device, your mobile operating system, the type of mobile Internet browser you\n" +
                "use, unique device identifiers and other diagnostic data.\n" +
                "\n" +
                "Tracking Cookies Data\n" +
                "We use cookies and similar tracking technologies to track the activity on our Service and we\n" +
                "hold certain information.\n" +
                "Cookies are files with a small amount of data which may include an anonymous unique\n" +
                "identifier. Cookies are sent to your browser from a website and stored on your device. Other\n" +
                "tracking technologies are also used such as beacons, tags and scripts to collect and track\n" +
                "information and to improve and analyze our Service.\n" +
                "You can instruct your browser to refuse all cookies or to indicate when a cookie is being\n" +
                "sent. However, if you do not accept cookies, you may not be able to use some portions of\n" +
                "our Service.\n" +
                "\n" +
                "Examples of Cookies we use:\n" +
                "(a) Session Cookies: We use Session Cookies to operate our Service.\n" +
                "\n" +
                "3\n" +
                "(b) Preference Cookies: We use Preference Cookies to remember your preferences and\n" +
                "various settings.\n" +
                "(c) Security Cookies: We use Security Cookies for security purposes.\n" +
                "(d) Advertising Cookies: Advertising Cookies are used to serve you with advertisements\n" +
                "that may be relevant to you and your interests.\n" +
                "\n" +
                "\n" +
                "5. Use of Data\n" +
                "WishRoll Inc. uses the collected data for various purposes:\n" +
                "(a) to provide and maintain our Service;\n" +
                "(b) to notify you about changes to our Service;\n" +
                "(c) to allow you to participate in interactive features of our Service when you choose to do\n" +
                "so;\n" +
                "(d) to provide customer support;\n" +
                "(e) to gather analysis or valuable information so that we can improve our Service;\n" +
                "(f) to monitor the usage of our Service;\n" +
                "(g) to detect, prevent and address technical issues;\n" +
                "(h) to fulfill any other purpose for which you provide it;\n" +
                "(i) to carry out our obligations and enforce our rights arising from any contracts entered into\n" +
                "between you and us, including for billing and collection;\n" +
                "(j) to provide you with notices about your account and/or subscription, including expiration\n" +
                "and renewal notices, email-instructions, etc.;\n" +
                "(k) to provide you with news, special offers and general information about other goods,\n" +
                "services and events which we offer that are similar to those that you have already\n" +
                "purchased or enquired about unless you have opted not to receive such information;\n" +
                "(l) in any other way we may describe when you provide the information;\n" +
                "(m) for any other purpose with your consent.\n" +
                "\n" +
                "\n" +
                "4\n" +
                "\n" +
                "6. Retention of Data\n" +
                "We will retain your Personal Data only for as long as is necessary for the purposes set out in\n" +
                "this Privacy Policy. We will retain and use your Personal Data to the extent necessary to\n" +
                "comply with our legal obligations (for example, if we are required to retain your data to\n" +
                "comply with applicable laws), resolve disputes, and enforce our legal agreements and\n" +
                "policies.\n" +
                "We will also retain Usage Data for internal analysis purposes. Usage Data is generally\n" +
                "retained for a shorter period, except when this data is used to strengthen the security or to\n" +
                "improve the functionality of our Service, or we are legally obligated to retain this data for\n" +
                "longer time periods.\n" +
                "\n" +
                "7. Transfer of Data\n" +
                "Your information, including Personal Data, may be transferred to – and maintained on –\n" +
                "computers located outside of your state, province, country or other governmental jurisdiction\n" +
                "where the data protection laws may differ from those of your jurisdiction.\n" +
                "If you are located outside United States and choose to provide information to us, please\n" +
                "note that we transfer the data, including Personal Data, to United States and process it\n" +
                "there.\n" +
                "\n" +
                "Your consent to this Privacy Policy followed by your submission of such information\n" +
                "represents your agreement to that transfer.\n" +
                "WishRoll Inc. will take all the steps reasonably necessary to ensure that your data is treated\n" +
                "securely and in accordance with this Privacy Policy and no transfer of your Personal Data\n" +
                "will take place to an organisation or a country unless there are adequate controls in place\n" +
                "including the security of your data and other personal information.\n" +
                "\n" +
                "8. Disclosure of Data\n" +
                "We may disclose personal information that we collect, or you provide:\n" +
                "(a) Business Transaction.\n" +
                "If we or our subsidiaries are involved in a merger, acquisition or asset sale, your\n" +
                "Personal Data may be transferred.\n" +
                "(b) Other cases. We may disclose your information also:\n" +
                "(i) to our subsidiaries and affiliates;\n" +
                "(ii) to contractors, service providers, and other third parties we use to support our\n" +
                "business;\n" +
                "(iii) to fulfill the purpose for which you provide it;\n" +
                "(iv) with your consent in any other cases;\n" +
                "\n" +
                "\n" +
                "5\n" +
                "(v) if we believe disclosure is necessary or appropriate to protect the rights, property, or\n" +
                "safety of the Company, our customers, or others.\n" +
                "\n" +
                "\n" +
                "9. Security of Data\n" +
                "The security of your data is important to us but remember that no method of transmission\n" +
                "over the Internet or method of electronic storage is 100% secure. While we strive to use\n" +
                "commercially acceptable means to protect your Personal Data, we cannot guarantee its\n" +
                "absolute security.\n" +
                "\n" +
                "10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)\n" +
                "If you are a resident of the European Union (EU) and European Economic Area (EEA), you\n" +
                "have certain data protection rights, covered by GDPR. – See more at https://eur-\n" +
                "lex.europa.eu/eli/reg/2016/679/oj\n" +
                "We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of\n" +
                "your Personal Data.\n" +
                "\n" +
                "If you wish to be informed what Personal Data we hold about you and if you want it to be\n" +
                "removed from our systems, please delete your account\n" +
                "In certain circumstances, you have the following data protection rights:\n" +
                "(a) the right to access, update or to delete the information we have on you;\n" +
                "(b) the right of rectification. You have the right to have your information rectified if that\n" +
                "information is inaccurate or incomplete;\n" +
                "(c) the right to object. You have the right to object to our processing of your Personal Data;\n" +
                "(d) the right of restriction. You have the right to request that we restrict the processing of\n" +
                "your personal information;\n" +
                "(e) the right to data portability. You have the right to be provided with a copy of your\n" +
                "Personal Data in a structured, machine-readable and commonly used format;\n" +
                "(f) the right to withdraw consent. You also have the right to withdraw your consent at any\n" +
                "time where we rely on your consent to process your personal information;\n" +
                "Please note that we may ask you to verify your identity before responding to such requests.\n" +
                "Please note, we may not able to provide Service without some necessary data.\n" +
                "You have the right to complain to a Data Protection Authority about our collection and use of\n" +
                "your Personal Data. For more information, please contact your local data protection\n" +
                "authority in the European Economic Area (EEA).\n" +
                "11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)\n" +
                "CalOPPA is the first state law in the nation to require commercial websites and online\n" +
                "services to post a privacy policy. The law’s reach stretches well beyond California to require\n" +
                "\n" +
                "\n" +
                "6\n" +
                "a person or company in the United States (and conceivable the world) that operates\n" +
                "websites collecting personally identifiable information from California consumers to post a\n" +
                "conspicuous privacy policy on its website stating exactly the information being collected and\n" +
                "those individuals with whom it is being shared, and to comply with this policy. – See more at:\n" +
                "https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-\n" +
                "protection-act-caloppa-3/\n" +
                "\n" +
                "According to CalOPPA we agree to the following:\n" +
                "(a) users can visit our site anonymously;\n" +
                "(b) our Privacy Policy link includes the word “Privacy”, and can easily be found on the page\n" +
                "specified above on the home page of our website;\n" +
                "(c) users will be notified of any privacy policy changes on our Privacy Policy Page;\n" +
                "Our Policy on “Do Not Track” Signals:\n" +
                "We honor Do Not Track signals and do not track, plant cookies, or use advertising when a\n" +
                "Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in\n" +
                "your web browser to inform websites that you do not want to be tracked.\n" +
                "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your\n" +
                "web browser.\n" +
                "\n" +
                "12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)\n" +
                "If you are a California resident, you are entitled to learn what data we collect about you, ask\n" +
                "to delete your data and not to sell (share) it. To exercise your data protection rights, you can\n" +
                "make certain requests and ask us:\n" +
                "(a) What personal information we have about you. If you make this request, we will\n" +
                "return to you:\n" +
                "(i) The categories of personal information we have collected about you.\n" +
                "(ii) The categories of sources from which we collect your personal information.\n" +
                "(iii) The business or commercial purpose for collecting or selling your personal\n" +
                "information.\n" +
                "(iv) The categories of third parties with whom we share personal information.\n" +
                "(v) The specific pieces of personal information we have collected about you.\n" +
                "(vi) A list of categories of personal information that we have sold, along with the category\n" +
                "of any other company we sold it to. If we have not sold your personal information, we\n" +
                "will inform you of that fact.\n" +
                "\n" +
                "\n" +
                "7\n" +
                "(vii) A list of categories of personal information that we have disclosed for a business\n" +
                "purpose, along with the category of any other company we shared it with.\n" +
                "Please note, you are entitled to ask us to provide you with this information up to two\n" +
                "times in a rolling twelve-month period. When you make this request, the information\n" +
                "provided may be limited to the personal information we collected about you in the\n" +
                "previous 12 months.\n" +
                "\n" +
                "(b) To delete your personal information. If you make this request, we will delete the\n" +
                "personal information we hold about you as of the date of your request from our records\n" +
                "and direct any service providers to do the same. In some cases, deletion may be\n" +
                "accomplished through de-identification of the information. If you choose to delete your\n" +
                "personal information, you may not be able to use certain functions that require your\n" +
                "personal information to operate.\n" +
                "\n" +
                "(c) To stop selling your personal information. We do not sell your personal information\n" +
                "for monetary consideration. However, under some circumstances, a transfer of personal\n" +
                "information to a third party, or within our family of companies, without monetary\n" +
                "consideration may be considered a “sale” under California law.\n" +
                "If you submit a request to stop selling your personal information, we will stop making\n" +
                "such transfers. If you are a California resident, to opt-out of the sale of your personal\n" +
                "information, click “Do Not Sell My Personal Information” at the bottom of our home page\n" +
                "to submit your request.\n" +
                "\n" +
                "To exercise your California data protection rights described above, please send your\n" +
                "request(s) by one of the following means:\n" +
                "By email: support@wishroll.co\n" +
                "By visiting this page on our website: https://wishroll.co/contact\n" +
                "Your data protection rights, described above, are covered by the CCPA, short for the\n" +
                "California Consumer Privacy Act. To find out more, visit the official California Legislative\n" +
                "Information website. The CCPA took effect on 01/01/2020.\n" +
                "13. Service Providers\n" +
                "\n" +
                "We may employ third party companies and individuals to facilitate our Service (“Service\n" +
                "Providers”), provide Service on our behalf, perform Service-related services or assist us in\n" +
                "analysing how our Service is used.\n" +
                "These third parties have access to your Personal Data only to perform these tasks on our\n" +
                "behalf and are obligated not to disclose or use it for any other purpose.\n" +
                "\n" +
                "\n" +
                "8\n" +
                "\n" +
                "14. Analytics\n" +
                "We may use third-party Service Providers to monitor and analyze the use of our Service.\n" +
                "\n" +
                "Firebase\n" +
                "Firebase is analytics service provided by Google Inc.\n" +
                "You may opt-out of certain Firebase features through your mobile device settings, such as\n" +
                "your device advertising settings or by following the instructions provided by Google in their\n" +
                "Privacy Policy: https://policies.google.com/privacy?hl=en\n" +
                "For more information on what type of information Firebase collects, please visit the Google\n" +
                "Privacy Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "Mixpanel\n" +
                "Mixpanel is provided by Mixpanel Inc.\n" +
                "You can prevent Mixpanel from using your information for analytics purposes by opting-out.\n" +
                "To opt-out of Mixpanel service, please visit this page: https://mixpanel.com/optout/\n" +
                "For more information on what type of information Mixpanel collects, please visit the Terms of\n" +
                "Use page of Mixpanel: https://mixpanel.com/terms/\n" +
                "15. CI/CD tools\n" +
                "We may use third-party Service Providers to automate the development process of our\n" +
                "Service.\n" +
                "\n" +
                "GitHub\n" +
                "GitHub is provided by GitHub, Inc.\n" +
                "GitHub is a development platform to host and review code, manage projects, and build\n" +
                "software.\n" +
                "\n" +
                "For more information on what data GitHub collects for what purpose and how the protection\n" +
                "of the data is ensured, please visit GitHub Privacy Policy page:\n" +
                "https://help.github.com/en/articles/github-privacy-statement.\n" +
                "GitLab CI/CD\n" +
                "GitLab CI/CD is provided by GitLab, Inc.\n" +
                "GitLab CI (Continuous Integration) service is a part of GitLab that build and test the software\n" +
                "whenever developer pushes code to application.\n" +
                "GitLab CD (Continuous Deployment) is a software service that places the changes of every\n" +
                "code in the production which results in every day deployment of production.\n" +
                "\n" +
                "9\n" +
                "For more information on what data GitLab CI/CD collects for what purpose and how the\n" +
                "protection of the data is ensured, please visit GitLab CI/CD Privacy Policy page:\n" +
                "https://about.gitlab.com/privacy/.\n" +
                "\n" +
                "16. Advertising\n" +
                "We may use third-party Service Providers to show advertisements to you to help support\n" +
                "and maintain our Service.\n" +
                "\n" +
                "Google AdSense DoubleClick Cookie\n" +
                "Google, as a third party vendor, uses cookies to serve ads on our Service. Google&#39;s use of\n" +
                "the DoubleClick cookie enables it and its partners to serve ads to our users based on their\n" +
                "visit to our Service or other websites on the Internet.\n" +
                "You may opt out of the use of the DoubleClick Cookie for interest-based advertising by\n" +
                "visiting the Google Ads Settings web page: http://www.google.com/ads/preferences/\n" +
                "\n" +
                "AdMob by Google\n" +
                "AdMob by Google is provided by Google Inc.\n" +
                "You can opt-out from the AdMob by Google service by following the instructions described\n" +
                "by Google: https://support.google.com/ads/answer/2662922?hl=en\n" +
                "For more information on how Google uses the collected information, please visit the “How\n" +
                "Google uses data when you use our partners&#39; sites or app” page:\n" +
                "http://www.google.com/policies/privacy/partners/ or visit the Privacy Policy of Google:\n" +
                "http://www.google.com/policies/privacy/\n" +
                "\n" +
                "17. Behavioral Remarketing\n" +
                "WishRoll Inc. uses remarketing services to advertise on third party websites to you after you\n" +
                "visited our Service. We and our third-party vendors use cookies to inform, optimise and\n" +
                "serve ads based on your past visits to our Service.\n" +
                "\n" +
                "Google Ads (AdWords)\n" +
                "Google Ads (AdWords) remarketing service is provided by Google Inc.\n" +
                "You can opt-out of Google Analytics for Display Advertising and customize the Google\n" +
                "Display Network ads by visiting the Google Ads Settings page:\n" +
                "http://www.google.com/settings/ads\n" +
                "Google also recommends installing the Google Analytics Opt-out Browser Add-on –\n" +
                "https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out\n" +
                "Browser Add-on provides visitors with the ability to prevent their data from being collected\n" +
                "and used by Google Analytics.\n" +
                "For more information on the privacy practices of Google, please visit the Google Privacy\n" +
                "\n" +
                "Terms web page: https://policies.google.com/privacy?hl=en\n" +
                "\n" +
                "Facebook\n" +
                "\n" +
                "Facebook remarketing service is provided by Facebook Inc.\n" +
                "\n" +
                "10\n" +
                "You can learn more about interest-based advertising from Facebook by visiting this page:\n" +
                "https://www.facebook.com/help/164968693837950\n" +
                "To opt-out from Facebook&#39;s interest-based ads, follow these instructions from Facebook:\n" +
                "https://www.facebook.com/help/568137493302217\n" +
                "Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising\n" +
                "established by the Digital Advertising Alliance. You can also opt-out from Facebook and\n" +
                "other participating companies through the Digital Advertising Alliance in the USA\n" +
                "http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada\n" +
                "http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe\n" +
                "http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.\n" +
                "For more information on the privacy practices of Facebook, please visit Facebook&#39;s Data\n" +
                "Policy: https://www.facebook.com/privacy/explanation\n" +
                "\n" +
                "18. Payments\n" +
                "We may provide paid products and/or services within Service. In that case, we use third-\n" +
                "party services for payment processing (e.g. payment processors).\n" +
                "We will not store or collect your payment card details. That information is provided directly to\n" +
                "our third-party payment processors whose use of your personal information is governed by\n" +
                "their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as\n" +
                "managed by the PCI Security Standards Council, which is a joint effort of brands like Visa,\n" +
                "Mastercard, American Express and Discover. PCI-DSS requirements help ensure the\n" +
                "secure handling of payment information.\n" +
                "The payment processors we work with are:\n" +
                "\n" +
                "PayPal or Braintree:\n" +
                "Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full\n" +
                "\n" +
                "Stripe:\n" +
                "Their Privacy Policy can be viewed at: https://stripe.com/us/privacy\n" +
                "\n" +
                "19. Links to Other Sites\n" +
                "Our Service may contain links to other sites that are not operated by us. If you click a third\n" +
                "party link, you will be directed to that third party&#39;s site. We strongly advise you to review the\n" +
                "Privacy Policy of every site you visit.\n" +
                "\n" +
                "We have no control over and assume no responsibility for the content, privacy policies or\n" +
                "practices of any third party sites or services.\n" +
                "\n" +
                "20. Children&#39;s Privacy\n" +
                "Our Services are not intended for use by children under the age of 13 (“Children”).\n" +
                "\n" +
                "11\n" +
                "We do not knowingly collect personally identifiable information from Children under 13. If\n" +
                "you become aware that a Child has provided us with Personal Data, please contact us. If we\n" +
                "become aware that ce have collected Personal Data from Children without verification of\n" +
                "parental consent, we take steps to remove that information from our servers.\n" +
                "\n" +
                "21. Changes to This Privacy Policy\n" +
                "We may update our Privacy Policy from time to time. We will notify you of any changes by\n" +
                "posting the new Privacy Policy on this page.\n" +
                "We will let you know via email and/or a prominent notice on our Service, prior to the change\n" +
                "becoming effective and update “effective date” at the top of this Privacy Policy.\n" +
                "You are advised to review this Privacy Policy periodically for any changes. Changes to this\n" +
                "Privacy Policy are effective when they are posted on this page.\n" +
                "\n" +
                "22. Contact Us\n" +
                "If you have any questions about this Privacy Policy, please contact us:\n" +
                "By email: support@wishroll.co.\n" +
                "By visiting this page on our website: https://wishroll.co/contact.";

        String rofl = "WishRoll Terms of Service\n" +
                "\n" +
                "Effective date: 02/05/2020\n" +
                "TERMS OF SERVICE\n" +
                "Last updated: 02/05/2020\n" +
                "\n" +
                "Introduction\n" +
                "Welcome to WishRoll Inc. (“Company”, “we”, “our”, “us”)! As you have just clicked to our Terms of Service, please make a pause, grab a cup of coffee and carefully read the following pages. It will take you approximately 20 minutes. \n" +
                "These Terms of Service (“Terms”, “Terms of Service”) govern your use of our mobile application WishRoll operated by WishRoll Inc. \n" +
                "Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web pages. Please read it here https://www.wishroll.co/privacy. \n" +
                "Your agreement with us includes these Terms and our Privacy Policy (“Agreements”). You acknowledge that you have read and understood Agreements, and agree to be bound of them. \n" +
                "If you do not agree with (or cannot comply with) Agreements, then you may not use the Service, but please let us know by emailing at support@wishroll.co so we can try to find a solution. These Terms apply to all visitors, users and others who wish to access or use Service. \n" +
                "Thank you for being responsible. \n" +
                "\n" +
                "Communications\n" +
                "By creating an Account on our Service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at. \n" +
                "\n" +
                "Purchases\n" +
                "If you wish to purchase any product or service made available through Service (“Purchase”), you may be asked to supply certain information relevant to your Purchase including, without limitation, your credit card number, the expiration date of your credit card, your billing address, and your shipping information. \n" +
                "You represent and warrant that: (i) you have the legal right to use any credit card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete. \n" +
                "We may employ the use of third party services for the purpose of facilitating payment and the completion of Purchases. By submitting your information, you grant us the right to provide the information to these third parties subject to our Privacy Policy. \n" +
                "We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: product or service availability, errors in the description or price of the product or service, error in your order or other reasons. \n" +
                "We reserve the right to refuse or cancel your order if fraud or an unauthorized or illegal transaction is suspected. \n" +
                "\n" +
                "Refunds\n" +
                "Except when required by law, paid Subscription fees are non-refundable. \n" +
                "Content\n" +
                "\n" +
                "Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (“Content”). You are responsible for Content that you post on or through Service, including its legality, reliability, and appropriateness. \n" +
                "By posting Content on or through Service, You represent and warrant that: (i) Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and license as provided in these Terms, and (ii) that the posting of your Content on or through Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the account of anyone found to be infringing on a copyright. \n" +
                "You retain any and all of your rights to any Content you submit, post or display on or through Service and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through Service. However, by posting Content using Service you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through Service. You agree that this license includes the right for us to make your Content available to other users of Service, who may also use your Content subject to these Terms. \n" +
                "WishRoll Inc. has the right but not the obligation to monitor and edit all Content provided by users. \n" +
                "In addition, Content found on or through this Service are the property of WishRoll Inc. or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us. \n" +
                "\n" +
                "Prohibited Uses\n" +
                "You may use Service only for lawful purposes and in accordance with Terms. You agree not to use Service: \n" +
                "In any way that violates any applicable national or international law or regulation. \n" +
                "For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise. To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter,” “spam,” or any other similar solicitation. To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity. In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity. To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of Service, or which, as determined by us, may harm or offend Company or users of Service or expose them to liability. Additionally, you agree not to: Use Service in any manner that could disable, overburden, damage, or impair Service or interfere with any other party’s use of Service, including their ability to engage in real time activities through Service. Use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service. Use any manual process to monitor or copy any of the material on Service or for any other unauthorized purpose without our prior written consent. Use any device, software, or routine that interferes with the proper working of Service. Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful. Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service. Attack Service via a denial-of-service attack or a distributed denial-of-service attack. Take any action that may damage or falsify Company rating. Otherwise attempt to interfere with the proper working of Service. \n" +
                "\n" +
                "Analytics \n" +
                "We may use third-party Service Providers to monitor and analyze the use of our Service. \n" +
                "\n" +
                "Google Analytics Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245. \n" +
                "\n" +
                "Firebase Firebase is analytics service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy?hl=en For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en \n" +
                "\n" +
                "Mixpanel\n" +
                "Mixpanel is provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page: https://mixpanel.com/optout/ For more information on what type of information Mixpanel collects, please visit the Terms of Use page of Mixpanel: https://mixpanel.com/terms/ \n" +
                "\n" +
                "No Use By Minors Service is intended only for access and use by individuals at least eighteen (18) years old. By accessing or using any of Company, you warrant and represent that you are at least eighteen (18) years of age and with the full authority, right, and capacity to enter into this agreement and abide by all of the terms and conditions of Terms. If you are not at least eighteen (18) years old, you are prohibited from both the access and usage of Service. \n" +
                "\n" +
                "Accounts When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on Service. You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account. You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene. We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in our sole discretion. \n" +
                "\n" +
                "Intellectual Property Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of WishRoll Inc. and its licensors. Service is protected by copyright, trademark, and other laws of the United States. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of WishRoll Inc.. \n" +
                "\n" +
                "Copyright Policy We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on Service infringes on the copyright or other intellectual property rights (“Infringement”) of any person or entity. If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement, please submit your claim via email to [●], with the subject line: “Copyright Infringement” and include in your claim a detailed description of the alleged Infringement as detailed below, under “DMCA Notice and Procedure for Copyright Infringement Claims” You may be held accountable for damages (including costs and attorneys' fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through Service on your copyright. \n" +
                "\n" +
                "DMCA Notice and Procedure for Copyright Infringement Claims You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail): an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright's interest;\n" +
                "a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work; identification of the URL or other specific location on Service where the material that you claim is infringing is located;\n" +
                "your address, telephone number, and email address;\n" +
                "a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. You can contact our Copyright Agent via email at [●] \n" +
                "\n" +
                "Error Reporting and Feedback You may provide us either directly at support@wishroll.co or via third party sites and tools with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service (“Feedback”). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialize) Feedback in any manner and for any purpose. The third party sites and tools mentioned above include the following: \n" +
                "\n" +
                "Bugsnag Bugsnag is a platform for monitoring and logging stability of applications provided by Bugsnag Inc. Please read their Privacy Policy here: https://docs.bugsnag.com/legal/privacy-policy/ \n" +
                "\n" +
                "Firebase Crashlytics Firebase Crashlytics is bug reporting service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy?hl=en For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en Links To Other Web Sites Our Service may contain links to third party web sites or services that are not owned or controlled by WishRoll Inc. WishRoll Inc. has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites. YOU ACKNOWLEDGE AND AGREE THAT WISHROLL INC. SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON \n" +
                "OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES. WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT. \n" +
                "\n" +
                "Disclaimer Of Warranty \n" +
                "THESE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE” BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. \n" +
                "YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK. NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE \n" +
                "ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, \n" +
                "THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT \n" +
                "THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. \n" +
                "\n" +
                "Limitation Of Liability\n" +
                "EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS' FEES AND ALL RELATED COSTS AND EXPENSES\n" +
                "OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, \n" +
                "OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM \n" +
                "THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY\n" +
                "HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS\n" +
                "LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO \n" +
                "CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, \n" +
                "SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. \n" +
                "\n" +
                "Termination\n" +
                "We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms. If you wish to terminate your account, you may simply discontinue using Service. All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. \n" +
                "\n" +
                "Governing Law\n" +
                "These Terms shall be governed and construed in accordance with the laws of State of New York without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. \n" +
                "These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service. \n" +
                "\n" +
                "Changes To Service\n" +
                "We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period.\n" +
                "From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users. \n" +
                "\n" +
                "Amendments To Terms\n" +
                "We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically. Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service. \n" +
                "\n" +
                "Waiver And Severability\n" +
                "No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision. If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect. \n" +
                "Acknowledgement BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM. \n" +
                "\n" +
                "Contact Us\n" +
                "Please send your feedback, comments, requests for technical support: By email: support@wishroll.co. By visiting this page on our website: https://www.wishroll.co/contact.";


            if (pageTitle == 1) {
                //view faq text
                mainTitle.setText(getResources().getString(R.string.faqs));
                findViewById(R.id.faqTextBody).setVisibility(View.VISIBLE);
                findViewById(R.id.privacyPolicyText).setVisibility(GONE);
                privacyPolicyBody.setVisibility(View.GONE);

            } else if (pageTitle == 2) {
                mainTitle.setText(getResources().getString(R.string.privacy_policy));
                findViewById(R.id.privacyPolicyText).setVisibility(View.VISIBLE);
                findViewById(R.id.faqTextBody).setVisibility(GONE);
                privacyPolicyBody.setVisibility(View.VISIBLE);
                privacyPolicyBody.setText(lol);
                Log.d(TAG, "onCreate: PRIVACY POLICY HOPEFULLY ITS ESCAPED ");
                //view privacy policy stuff
            } else if (pageTitle == 3) {
                mainTitle.setText(getResources().getString(R.string.terms_of_service));
                findViewById(R.id.privacyPolicyText).setVisibility(View.VISIBLE);
                findViewById(R.id.faqTextBody).setVisibility(GONE);
                privacyPolicyBody.setVisibility(View.VISIBLE);
                privacyPolicyBody.setText(rofl);
                Log.d(TAG, "onCreate: PRIVACY POLICY HOPEFULLY ITS ESCAPED ");
            } else {
                mainTitle.setVisibility(GONE);
                findViewById(R.id.privacyPolicyText).setVisibility(View.GONE);
                findViewById(R.id.faqTextBody).setVisibility(GONE);
                privacyPolicyBody.setVisibility(GONE);
            }

    }

}